# Generated by Django 4.2.11 on 2025-07-30 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_name', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=20)),
                ('email', models.EmailField(default=None, max_length=254)),
                ('address', models.CharField(max_length=200)),
                ('gst_no', models.CharField(max_length=40)),
            ],
        ),
    ]
