# Generated by Django 4.2.11 on 2025-07-30 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tempo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(max_length=20)),
                ('party_name', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=200)),
                ('vehicle_type', models.CharField(max_length=10)),
            ],
        ),
    ]
