# Generated by Django 4.2.11 on 2025-07-30 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tempo', '0002_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='ownership',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='address',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='contact_number',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='party_name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_number',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
