# Generated by Django 4.2.11 on 2025-08-02 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tempo', '0004_master'),
    ]

    operations = [
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_number', models.CharField(default=None, max_length=50)),
                ('booking_date', models.DateField()),
                ('our_gst', models.CharField(max_length=30)),
                ('total_hire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('advance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hamali', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tds', models.DecimalField(decimal_places=2, max_digits=10)),
                ('st_charges', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commission', models.DecimalField(decimal_places=2, max_digits=10)),
                ('other_charges', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('myExpense', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('profit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('remark', models.CharField(max_length=100)),
                ('master_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tempo.master')),
                ('party_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tempo.party')),
                ('vehicle_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tempo.vehicle')),
            ],
        ),
    ]
