# Generated by Django 4.2.11 on 2025-08-02 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tempo', '0005_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='master_id',
        ),
        migrations.AddField(
            model_name='booking',
            name='from_city',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='bookings_as_from_city', to='tempo.master'),
        ),
        migrations.AddField(
            model_name='booking',
            name='to_city',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='bookings_as_to_city', to='tempo.master'),
        ),
    ]
