# Generated by Django 4.2.11 on 2025-08-02 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tempo', '0006_remove_booking_master_id_booking_from_city_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='from_city',
            new_name='from_city_id',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='party_id',
            new_name='party_id_id',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='to_city',
            new_name='to_city_id',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='vehicle_id',
            new_name='vehicle_id_id',
        ),
    ]
