# Generated by Django 4.2.11 on 2025-08-02 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tempo', '0007_rename_from_city_booking_from_city_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='from_city_id',
            new_name='from_city',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='party_id_id',
            new_name='party',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='to_city_id',
            new_name='to_city',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='vehicle_id_id',
            new_name='vehicle',
        ),
        migrations.AlterField(
            model_name='master',
            name='city',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
