# Generated by Django 4.2.11 on 2025-08-03 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tempo', '0008_rename_from_city_id_booking_from_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('customer_mobile', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('customer_email', models.EmailField(max_length=254, unique=True)),
                ('customer_photo', models.ImageField(default=None, upload_to='static/')),
                ('customer_password', models.CharField(max_length=100)),
            ],
        ),
    ]
