# Generated by Django 4.2.11 on 2025-08-04 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tempo', '0009_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_gst',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
