# Generated by Django 4.2.11 on 2025-08-10 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tempo', '0010_customer_customer_gst'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='profit',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='total_hire',
            field=models.IntegerField(),
        ),
    ]
