# Generated by Django 4.2.11 on 2025-08-13 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tempo', '0011_alter_booking_profit_alter_booking_total_hire'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
