# Generated by Django 4.2.11 on 2025-08-19 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tempo', '0012_booking_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_number',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
