# Generated by Django 4.2.11 on 2025-08-21 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tempo', '0013_alter_booking_booking_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='contact_number',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
