# Generated by Django 4.2.11 on 2025-08-22 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tempo', '0014_alter_party_contact_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
